
info:
  app:
    version: "@project.version@"
    
logging:
 level:
  web: DEBUG
  org.springframework: INFO
  org.springframework.security: DEBUG
  
spring:
 security:
#  user:
#   password: senha   
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    #url: jdbc:h2:mem:titherdb
    url: jdbc:h2:file:./data/titherdb
    driverClassName: org.h2.Driver
    username: sa
    password: senha   
   